# Generated by Django 3.2 on 2021-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sended_notification',
            field=models.BooleanField(default=False),
        ),
    ]
